# -*- coding: utf-8 -*-
"""BScraper1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4q23-inv0VP5w2nMyzzzW2C0qExtNIJ
"""

import requests
import json
from bs4 import BeautifulSoup

url = "https://covid19.who.int/table"
req = requests.get(url)
doc = BeautifulSoup(req.text, 'html.parser')

found_daily_deaths = doc.find_all("div",{"class": "column_Last_7_Days_Deaths td"})
found_cumulative_deaths = doc.find_all("div",{"class": "column_Cumulative_Deaths td"})
found_countries = doc.find_all("div",{"class": "column_name td"})

countries = []
cumulative_deaths = []
daily_deaths = []
for i in range(len(found_countries)):
  if found_countries[i].text[0] == '+':
    continue

  countries.append(found_countries[i].text)

  if found_cumulative_deaths[i].text == '':
    cumulative_deaths.append("N/A")
  else:
    cumulative_deaths.append(found_cumulative_deaths[i].text)

  if found_daily_deaths[i].text == '':
    daily_deaths.append("N/A")
  else:
    daily_deaths.append(found_daily_deaths[i].text)

data = {
    "Country": countries,
    "Cumulative Deaths": cumulative_deaths,
    "Daily Deaths": daily_deaths
}

json_object = json.dumps(data, indent=4)
 
with open("Covid_data1.json", "w") as outfile:
    outfile.write(json_object)